@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJteSBKV1QgdG9rZW4gZnJvbSBodW50In0.XvWmEPZViqVkwMuZEpRBq2Owi8qLR9HUZI9Knyb1x4I
@hunt_url = http://localhost:3000

### GET user profile
get {{hunt_url}}/api/profile HTTP/1.1
Authorization: token {{jwt}}

### Switch my favorite film
put {{hunt_url}}/api/favorite?18 HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

1599

### GET films
get {{hunt_url}}/api/film HTTP/1.1
Authorization: token {{jwt}}

### Update user profile
put {{hunt_url}}/api/profile HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

{
  "id": 14813,
  "my_films": [
    {
      "id": 15447,
      "type": "favorite",
      "cassettes": [
        {
          "id": 41
        },
        {
          "id": 43
        },
        {
          "id": 419
        },
        {
          "id": 42
        }
      ]
    }
  ]
}
