# @hunt_url = https://hunt.poff.ee
@hunt_url = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1paGtlbC5wdXRyaW5zaEBnbWFpbC5jb20iLCJjb25maXJtZWQiOnRydWUsInByb2ZpbGUiOnRydWUsImZpcnN0TmFtZSI6Ik1paGtlbCIsImxhc3ROYW1lIjoiUHV0cmluxaEiLCJpYXQiOjE2OTgyNDg2OTIsIm5iZiI6MTY5ODI0ODY5MiwiZXhwIjoxNjk5NDU4MjkyLCJzdWIiOiIxNDgxMyJ9.qPogbNyQN0y7Hm1CkUzm9JVcTCZFh-0aPi2a5JUPIBk

### GET user profile
get {{hunt_url}}/api/me HTTP/1.1
Authorization: token {{jwt}}

### Get my favorite films
get {{hunt_url}}/api/my/film HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

### Switch my favorite film
put {{hunt_url}}/api/my/film HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

1599

### Switch my screening
put {{hunt_url}}/api/my/screening HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

2366

### Merge My over all my users
# gmail 14813
# poff 17339
put {{hunt_url}}/api/me/link HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

17339

### GET strapi cinemas
get https://admin.poff.ee/cinemas HTTP/1.1
Authorization: token {{jwt}}

### GET films with limit and page
### default limit is -1 and page is 1
get {{hunt_url}}/api/film?limit=1 HTTP/1.1
Authorization: token {{jwt}}

### GET cassettes with limit and page
### default limit is -1 and page is 1
get {{hunt_url}}/api/cassette?limit=1 HTTP/1.1
Authorization: token {{jwt}}

### GET cinemas
get {{hunt_url}}/api/cinema HTTP/1.1
Authorization: token {{jwt}}

### Update user profile
put {{hunt_url}}/api/profile HTTP/1.1
Authorization: token {{jwt}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="60x60bb.jpg"
Content-Type: image/jpg

< ./JonDoe.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstName"

Jon
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastName"

Doe
------WebKitFormBoundary7MA4YWxkTrZu0gW--
