@hunt_url = http://localhost:3000

### GET user profile
get {{hunt_url}}/api/profile HTTP/1.1
Authorization: token {{jwt}}

### Switch my favorite film
put {{hunt_url}}/api/my/film HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

1599

### Switch my screening
put {{hunt_url}}/api/my/screening HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

2366

### GET films
get {{hunt_url}}/api/film HTTP/1.1
Authorization: token {{jwt}}

### GET cinemas
get {{hunt_url}}/api/cinema HTTP/1.1
Authorization: token {{jwt}}

### Update user profile
put {{hunt_url}}/api/profile HTTP/1.1
Authorization: token {{jwt}}
Content-Type: application/json

{
  "id": 14813,
  "username": "Mihkel-Mikelis Putrinš",
  "My": {
    "id": 1,
    "favorites": [
      { "id": 20 },
      { "id": 3792 }
    ],
    "screenings": [
      { "id": 1670 },
      { "id": 2366 },
      { "id": 2766 }
    ]
  }
}
