/**
 * All user-visible strings for the checkout flow, in three languages.
 * Usage: const copy = useCheckoutCopy(locale)  — locale is a Ref<string>
 */
export function useCheckoutCopy (locale) {
  return computed(() => {
    const ru = locale.value === 'ru'
    const et = locale.value === 'et'
    return {
      secureCheckout: ru ? 'Безопасное оформление' : et ? 'Turvaline ostuvorm' : 'Secure checkout',
      cart: ru ? 'Корзина' : et ? 'Ostukorv' : 'Cart',
      details: ru ? 'Детали товаров' : et ? 'Toodete andmed' : 'Item details',
      invoice: ru ? 'Счет' : et ? 'Arve' : 'Invoice',
      payment: ru ? 'Оплата' : et ? 'Maksmine' : 'Payment',
      payStep: ru ? 'Оплата' : et ? 'Maksa' : 'Pay',
      invoiceDetails: ru ? 'Данные счета' : et ? 'Arve andmed' : 'Invoice details',
      taxDocument: ru ? 'Налоговый документ' : et ? 'Maksudokument' : 'Tax document',
      chooseSavedProfile: ru ? 'Выберите сохраненный профиль' : et ? 'Vali salvestatud profiil' : 'Choose a saved profile',
      confirmPurchase: ru ? 'Подтверждение покупки' : et ? 'Kinnita ost' : 'Confirm purchase',
      pickup: ru ? 'Получение' : et ? 'Kättesaamine' : 'Pickup',
      owner: ru ? 'Владелец' : et ? 'Omanik' : 'Owner',
      pickupLocation: ru ? 'Место получения' : et ? 'Kättesaamise koht' : 'Pickup location',
      continue: ru ? 'Продолжить' : et ? 'Jätka' : 'Continue',
      back: ru ? 'Назад' : et ? 'Tagasi' : 'Back',
      pay: ru ? 'Оплатить' : et ? 'Maksa' : 'Pay',
      remove: ru ? 'Удалить' : et ? 'Eemalda' : 'Remove',
      choosePickup: ru ? 'Выберите место получения' : et ? 'Vali kättesaamise koht' : 'Choose pickup location',
      productOwner: ru ? 'Владелец товара' : et ? 'Toote omanik' : 'Product owner',
      forMe: ru ? 'Для меня' : et ? 'Mulle' : 'For me',
      forSomeoneElse: ru ? 'Для другого' : et ? 'Kellelegi teisele' : 'For someone else',
      whoInvoiceFor: ru ? 'Для кого счет?' : et ? 'Kellele arve?' : 'Who is the invoice for?',
      gift: ru ? 'В подарок' : et ? 'Kingituseks' : 'As a gift',
      firstName: ru ? 'Имя' : et ? 'Eesnimi' : 'First name',
      lastName: ru ? 'Фамилия' : et ? 'Perekonnanimi' : 'Last name',
      email: ru ? 'Э-почта' : et ? 'E-post' : 'Email',
      photo: ru ? 'Фото для пропуска' : et ? 'Foto passile' : 'Photo for the pass',
      photoPlaceholder: ru ? 'ФОТО' : et ? 'FOTO' : 'PHOTO',
      chooseFile: ru ? 'Выбрать файл' : et ? 'Vali fail' : 'Choose file',
      uploadPassPhoto: ru ? 'Загрузить фото для пропуска' : et ? 'Laadi üles passifoto' : 'Upload pass photo',
      photoHelp: ru ? 'JPG или PNG, от 600×600 до 3000×3000px, до 5 МБ. Лицо по центру, нейтральный фон.' : et ? 'JPG või PNG, 600×600 kuni 3000×3000px, kuni 5 MB. Nägu keskel, neutraalne taust.' : 'JPG or PNG, 600×600 to 3000×3000px, up to 5 MB. Face centered, neutral background.',
      photoNotImage: ru ? 'Пожалуйста, выберите файл изображения.' : et ? 'Palun vali pildifail.' : 'Please choose an image file.',
      photoTooLarge: ru ? 'Изображение слишком большое (максимум 5 МБ).' : et ? 'Pilt on liiga suur (kuni 5 MB).' : 'Image is too large (max 5 MB).',
      photoWrongSize: ru ? 'Размер изображения должен быть от 600×600 до 3000×3000px.' : et ? 'Pildi suurus peab olema 600×600 kuni 3000×3000px.' : 'Image must be between 600×600 and 3000×3000px.',
      replaceFile: ru ? 'Заменить' : et ? 'Asenda' : 'Replace',
      suppressEmail: ru ? 'Не отправлять уведомление' : et ? 'Ära saada teavituskirja' : "Don't send notification email",
      suppressEmailHint: ru ? 'Сохраните сюрприз — мы дадим PDF-подтверждение, которое можно передать самостоятельно.' : et ? 'Hoia see üllatusena — anname PDF-kinnituse, mille saad ise edasi anda.' : "Keep it a surprise — we'll give you a PDF confirmation you can pass along yourself.",
      savedProfiles: ru ? 'Сохраненные профили счета' : et ? 'Salvestatud arveprofiilid' : 'Saved invoice profiles',
      addPersonal: ru ? 'Добавить профиль частного лица' : et ? 'Lisa uus eraisiku arveprofiil' : 'Add personal invoice profile',
      addOrganisation: ru ? 'Добавить профиль организации' : et ? 'Lisa uus organisatsiooni arveprofiil' : 'Add organisation invoice profile',
      personal: ru ? 'Частное лицо' : et ? 'Eraisik' : 'Personal',
      organisation: ru ? 'Организация' : et ? 'Organisatsioon' : 'Organisation',
      saveProfile: ru ? 'Сохранить профиль' : et ? 'Salvesta profiil' : 'Save profile',
      saveAsProfile: ru ? 'Сохранить как профиль счета' : et ? 'Salvesta arveprofiilina' : 'Save as invoice profile',
      saveAsProfileHint: ru ? 'Данные сохранятся для следующих покупок.' : et ? 'Andmed salvestatakse järgmisteks ostudeks.' : "You won't need to re-enter details on your next purchase.",
      savedProfile: ru ? 'Профиль счета' : et ? 'Arveprofiil' : 'Invoice profile',
      newProfile: ru ? 'Новый профиль счета' : et ? 'Uus arveprofiil' : 'New invoice profile',
      willBeSaved: ru ? 'Будет сохранено в вашем аккаунте.' : et ? 'Salvestatakse sinu kontole.' : 'Will be saved to your account for next time.',
      changesSaved: ru ? 'Изменения будут сохранены при продолжении.' : et ? 'Muudatused salvestatakse jätkamisel.' : 'Changes will be saved when you continue.',
      change: ru ? 'Изменить' : et ? 'Muuda' : 'Change',
      companyName: ru ? 'Название компании' : et ? 'Ettevõtte nimi' : 'Company name',
      registryCode: ru ? 'Регистрационный код' : et ? 'Registrikood' : 'Registry code',
      vatNumber: ru ? 'Номер НДС' : et ? 'KMKR number' : 'VAT number',
      contactPerson: ru ? 'Контактное лицо' : et ? 'Kontaktisik' : 'Contact person',
      phone: ru ? 'Телефон' : et ? 'Telefon' : 'Phone',
      country: ru ? 'Страна' : et ? 'Riik' : 'Country',
      address: ru ? 'Адрес' : et ? 'Aadress' : 'Address',
      city: ru ? 'Город' : et ? 'Linn' : 'City',
      postalCode: ru ? 'Почтовый индекс' : et ? 'Postiindeks' : 'Postal code',
      choosePayment: ru ? 'Выберите способ оплаты' : et ? 'Vali makseviis' : 'Choose a payment method',
      bankTransfer: ru ? 'Банковский перевод' : et ? 'Pangaülekanne' : 'Bank transfer',
      cardPayment: ru ? 'Оплата картой' : et ? 'Kaardimakse' : 'Card payment',
      otherPayments: ru ? 'Другие способы' : et ? 'Muud maksed' : 'Other methods',
      payLaterLabel: ru ? 'Купи сейчас, плати потом' : et ? 'Osta nüüd, maksa hiljem' : 'Pay later',
      itemCount: ru ? 'Товары' : et ? 'Tooted' : 'Items',
      invoiceRecipient: ru ? 'Получатель счета' : et ? 'Arve saaja' : 'Invoice recipient',
      giftFieldsRequired: ru ? 'Заполните имя, э-почту и фото получателя.' : et ? 'Täida saaja nimi, e-post ja foto.' : 'Please fill recipient name, email and photo.',
      chooseInvoiceProfile: ru ? 'Выберите или добавьте профиль счета.' : et ? 'Vali või lisa arveprofiil.' : 'Please choose or add an invoice profile.',
      total: ru ? 'Итого' : et ? 'Kokku' : 'Total',
      terms: ru ? 'Я прочитал(а) и согласен(на) с условиями интернет-магазина' : et ? 'Olen lugenud internetipoe tingimusi ja nõustun nendega' : 'I have read and agree with terms of use of internet shop',
      empty: ru ? 'Корзина пуста' : et ? 'Ostukorv on tühi' : 'Your cart is empty',
      completeOrder: ru ? 'Завершите заказ' : et ? 'Lõpeta tellimus' : 'Complete your order',
      backToShop: ru ? 'Назад в магазин' : et ? 'Tagasi poodi' : 'Back to shop',
      holdCart: ru ? 'Мы держим вашу корзину 30 минут бездействия.' : et ? 'Hoiame sinu ostukorvi 30 minutit tegevusetust.' : 'We hold your cart for 30 minutes of inactivity.',
      session: ru ? 'Сессия' : et ? 'Sessioon' : 'Session',
      sessionFewMinutes: ru ? 'Осталось несколько минут в сессии оформления.' : et ? 'Ostusessioonis on jäänud vaid mõned minutid.' : 'A few minutes left in your checkout session.',
      sessionHurry: ru ? 'Поторопитесь — ваша сессия скоро закончится.' : et ? 'Kiirusta — sinu sessioon aegub peagi.' : 'Hurry — your session will expire soon.',
      sessionFinal: ru ? 'Последние секунды, чтобы сохранить корзину.' : et ? 'Viimased sekundid ostukorvi säilitamiseks.' : 'Final seconds to keep your cart.',
      sessionAboutToExpire: ru ? 'Ваша сессия скоро закончится' : et ? 'Sinu sessioon hakkab aeguma' : 'Your session is about to expire',
      sessionClearedIn: ru ? 'Ваша корзина будет очищена через' : et ? 'Sinu ostukorv tühjendatakse pärast' : 'Your cart will be cleared in',
      keepCart: ru ? 'Сохранить корзину · продолжить сессию' : et ? 'Hoia ostukorv · jätka sessiooni' : 'Keep my cart · resume session',
      dismiss: ru ? 'Закрыть' : et ? 'Sulge' : 'Dismiss',
      sessionExpiredTitle: ru ? 'Ваша корзина истекла' : et ? 'Sinu ostukorv aegus' : 'Your cart has expired',
      sessionExpiredText: ru ? 'Ваша сессия закончилась после 30 минут бездействия, и корзина была очищена. Вы можете начать новый заказ в магазине.' : et ? 'Sinu sessioon lõppes pärast 30 minutit tegevusetust ja ostukorv tühjendati. Saad alustada uut tellimust poest.' : 'Your session ended after 30 minutes of inactivity and your cart was cleared. You can start a new order from the shop.',
      needsDetails: ru ? 'Каждый товар требует дополнительных данных. Место получения обязательно.' : et ? 'Iga toode vajab lisaandmeid. Kättesaamise koht on kohustuslik.' : 'Each item in your cart needs some details before we can proceed. Pickup location is required.',
      stepLabel: ru ? 'ШАГ' : et ? 'SAMM' : 'STEP',
      complete: ru ? 'выполнено' : et ? 'valmis' : 'complete',
      chooseLocation: ru ? 'Выберите место' : et ? 'Vali asukoht' : 'choose location',
      me: ru ? 'Я' : et ? 'Mina' : 'Me',
      order: ru ? 'Заказ' : et ? 'Tellimus' : 'Order',
      subtotal: ru ? 'Промежуточный итог' : et ? 'Vahesumma' : 'Subtotal',
      vatIncluded: ru ? 'НДС 24% включен' : et ? 'KM 24% sisaldub' : 'VAT 24% (incl.)',
      noPickupNeeded: ru ? 'Место получения не требуется' : et ? 'Kättesaamise kohta pole vaja' : 'No pickup location required',
      ownerReady: ru ? 'Владелец' : et ? 'Omanik' : 'Owner',
      itemComplete: ru ? 'Готово' : et ? 'Valmis' : 'Complete',
      itemIncomplete: ru ? 'Нужно заполнить' : et ? 'Vajab täitmist' : 'Needs details',
      help: ru ? 'Нужна помощь?' : et ? 'Vajad abi?' : 'Need help?',
      orderConfirmedTitle: ru ? 'Спасибо — ваша покупка подтверждена!' : et ? 'Aitäh — sinu ost on kinnitatud!' : 'Thanks — your purchase is confirmed!',
      orderConfirmedText: ru ? 'Подтверждение и счёт отправлены на вашу почту. Товары готовы к получению в выбранных местах.' : et ? 'Kinnitus ja arve on saadetud sinu e-postile. Tooted on valmis kättesaamiseks valitud kohtades.' : 'Confirmation and invoice sent to your email. Items are ready for pickup at the locations you chose.',
      startAgain: ru ? 'Начать заново' : et ? 'Alusta uuesti' : 'Start again',
      paymentCancelledTitle: ru ? 'Платёж отменён' : et ? 'Makse katkestatud' : 'Payment was cancelled',
      paymentCancelledText: ru ? 'Вы можете попробовать снова или выбрать другой способ оплаты.' : et ? 'Saad uuesti proovida või valida teise makseviisi.' : 'You can try again or choose a different payment method.',
      tryAgain: ru ? 'Попробовать снова' : et ? 'Proovi uuesti' : 'Try again',
      // ── Success / order confirmed view ──
      paymentReceived: ru ? 'Платёж получен' : et ? 'Makse laekus' : 'Payment received',
      orderConfirmedHeading: ru ? 'Ваш заказ подтверждён' : et ? 'Sinu tellimus on kinnitatud' : 'Your order is confirmed',
      invoiceOnWay: ru ? 'Подтверждение и счёт с НДС уже в пути' : et ? 'Kinnitus ja käibemaksuarve on teel' : 'A confirmation and VAT invoice are on their way',
      invoiceOnWayTo: ru ? 'на' : et ? 'aadressile' : 'to',
      orderSummary: ru ? 'Сводка заказа' : et ? 'Tellimuse kokkuvõte' : 'Order summary',
      deliveredByEmail: ru ? 'Доставка по эл. почте' : et ? 'Saadetakse e-postiga' : 'Delivered by email',
      giftTo: ru ? 'Подарок для' : et ? 'Kingitus' : 'Gift to',
      paidWith: ru ? 'Оплачено через' : et ? 'Makstud' : 'Paid with',
      totalPaid: ru ? 'Итого оплачено' : et ? 'Kokku makstud' : 'Total paid',
      pickupNoticeTitle: ru ? 'Получение с 5 ноября.' : et ? 'Kättesaamine alates 5. novembrist.' : 'Pick up from November 5th.',
      pickupNoticeText: ru ? 'Покажите номер заказа или QR-код из письма в пункте выдачи.' : et ? 'Näita kättesaamiskohas oma tellimuse numbrit või e-kirja QR-koodi.' : 'Show your order number or the QR code from your email at the collection point.',
      goToMyPoff: ru ? 'Перейти в Мой PÖFF' : et ? 'Mine Minu PÖFF' : 'Go to My PÖFF',
      startNewOrder: ru ? 'Начать новый заказ' : et ? 'Alusta uut tellimust' : 'Start a new order',
      questionsAbout: ru ? 'Вопросы о заказе?' : et ? 'Küsimused tellimuse kohta?' : 'Questions about your order?',
      // ── Profile step ──
      yourProfile: ru ? 'Ваш профиль' : et ? 'Sinu profiil' : 'Your profile',
      profileIntro: ru ? 'Нам нужно несколько данных перед оформлением покупки.' : et ? 'Vajame enne ostmist mõnda andmet.' : 'We need a few details before your purchase.',
      saveAndContinue: ru ? 'Сохранить и продолжить' : et ? 'Salvesta ja jätka' : 'Save and continue',
      savingProfile: ru ? 'Сохранение...' : et ? 'Salvestamine...' : 'Saving...'
    }
  })
}
